/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Timer;
import java.lang.reflect.InvocationTargetException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class CheckClient1 extends javax.swing.JFrame {
   
    
    public CheckClient1() {
       
        setIconImage(new ImageIcon("src/icons/applogo.png").getImage());
        initComponents();       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        clear = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        colse = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        RegisterNewPatient2 = new javax.swing.JButton();
        ViewPatientRecord2 = new javax.swing.JButton();
        CreatePrescription2 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AddConsultation2 = new javax.swing.JButton();
        RecordVaccination2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuickLab");
        setBackground(new java.awt.Color(0, 115, 194));
        setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-user-folder-55.png"))); // NOI18N
        jLabel14.setText("Records");
        jLabel14.setIconTextGap(20);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 680, 60));

        first_name.setBackground(new java.awt.Color(0, 143, 253));
        jPanel1.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 300, 60));

        last_name.setBackground(new java.awt.Color(0, 143, 253));
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });
        jPanel1.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 300, 60));

        jButton8.setBackground(new java.awt.Color(0, 105, 170));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-search-client-24.png"))); // NOI18N
        jButton8.setText("Searche");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setDoubleBuffered(true);
        jButton8.setIconTextGap(5);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 140, 50));
        jButton4.setFocusPainted(false);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.setBackground(new Color(255, 255, 255)); // Set default background to white

        jButton4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jButton4.setBackground(new Color(240,240,240)); // Change to light gray on hover
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButton4.setBackground(new Color(255, 255, 255)); // Revert to white when not hovered
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Last name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("First name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jTableClient.setBackground(new java.awt.Color(91, 136, 201));
        jTableClient.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTableClient.setForeground(new java.awt.Color(51, 51, 51));
        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First name", "Last name", "Birth day", "SSN"
            }
        ));
        jTableClient.setAlignmentX(1.0F);
        jTableClient.setAlignmentY(1.0F);
        jTableClient.setGridColor(new java.awt.Color(51, 255, 204));
        jTableClient.setRowHeight(30);
        jTableClient.setSelectionBackground(new java.awt.Color(0, 0, 102));
        jTableClient.setSelectionForeground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTableClient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 1040, 660));

        clear.setBackground(new java.awt.Color(0, 105, 170));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear All");
        clear.setBorder(null);
        clear.setBorderPainted(false);
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.setDoubleBuffered(true);
        clear.setIconTextGap(5);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 140, 50));
        jButton4.setFocusPainted(false);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.setBackground(new Color(255, 255, 255)); // Set default background to white

        jButton4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jButton4.setBackground(new Color(240,240,240)); // Change to light gray on hover
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButton4.setBackground(new Color(255, 255, 255)); // Revert to white when not hovered
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 105, 170));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Show Record");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setDoubleBuffered(true);
        jButton9.setIconTextGap(5);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 820, 300, 50));
        jButton4.setFocusPainted(false);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.setBackground(new Color(255, 255, 255)); // Set default background to white

        jButton4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jButton4.setBackground(new Color(240,240,240)); // Change to light gray on hover
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButton4.setBackground(new Color(255, 255, 255)); // Revert to white when not hovered
            }
        });

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 1600, 1000));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(0, 0, 0));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-minimize-30.png"))); // NOI18N
        minimize.setBorder(null);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 0, 40, 40));
        minimize.setFocusPainted(false);
        minimize.setBorderPainted(false);
        minimize.setContentAreaFilled(false);
        minimize.setOpaque(true);

        minimize.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                minimize.setBackground(new Color(20,20,20)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                minimize.setBackground(new Color(0, 0,0)); // Original color when mouse not hovering
            }
        });

        colse.setBackground(new java.awt.Color(0, 0, 0));
        colse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-close-30.png"))); // NOI18N
        colse.setBorder(null);
        colse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colseActionPerformed(evt);
            }
        });
        jPanel2.add(colse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 0, 40, 40));
        colse.setFocusPainted(false);
        colse.setBorderPainted(false);
        colse.setContentAreaFilled(false);
        colse.setOpaque(true);

        colse.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                colse.setBackground(new Color(20,20,20)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                colse.setBackground(new Color(0, 0,0)); // Original color when mouse not hovering
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("QuickLab");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 40));

        jPanel4.setBackground(new java.awt.Color(0, 98, 166));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 115, 194));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-log-out-30.png"))); // NOI18N
        jButton4.setText("Disconnect");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setDoubleBuffered(true);
        jButton4.setIconTextGap(5);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 901, 220, 60));
        jButton4.setFocusPainted(false);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.setBackground(new Color(255, 255, 255)); // Set default background to white

        jButton4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jButton4.setBackground(new Color(240,240,240)); // Change to light gray on hover
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButton4.setBackground(new Color(255, 255, 255)); // Revert to white when not hovered
            }
        });

        RegisterNewPatient2.setBackground(new java.awt.Color(0, 105, 170));
        RegisterNewPatient2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegisterNewPatient2.setForeground(new java.awt.Color(255, 255, 255));
        RegisterNewPatient2.setText("Register a New Patient");
        RegisterNewPatient2.setToolTipText("");
        RegisterNewPatient2.setBorder(null);
        RegisterNewPatient2.setBorderPainted(false);
        RegisterNewPatient2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterNewPatient2.setDoubleBuffered(true);
        RegisterNewPatient2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterNewPatient2.setIconTextGap(50);
        RegisterNewPatient2.setName(""); // NOI18N
        RegisterNewPatient2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegisterNewPatient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterNewPatient2ActionPerformed(evt);
            }
        });
        jPanel4.add(RegisterNewPatient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 320, 70));
        RegisterNewPatient2.setFocusPainted(false);
        RegisterNewPatient2.setBorderPainted(false);
        RegisterNewPatient2.setContentAreaFilled(false);
        RegisterNewPatient2.setOpaque(true);

        RegisterNewPatient2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                RegisterNewPatient2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                RegisterNewPatient2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        ViewPatientRecord2.setBackground(new java.awt.Color(0, 120, 200));
        ViewPatientRecord2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewPatientRecord2.setForeground(new java.awt.Color(255, 255, 255));
        ViewPatientRecord2.setText("View Patient Record");
        ViewPatientRecord2.setBorder(null);
        ViewPatientRecord2.setBorderPainted(false);
        ViewPatientRecord2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewPatientRecord2.setDoubleBuffered(true);
        ViewPatientRecord2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ViewPatientRecord2.setIconTextGap(50);
        ViewPatientRecord2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ViewPatientRecord2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPatientRecord2ActionPerformed(evt);
            }
        });
        jPanel4.add(ViewPatientRecord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 320, 70));
        ViewPatientRecord2.setFocusPainted(false);
        ViewPatientRecord2.setBorderPainted(false);
        ViewPatientRecord2.setContentAreaFilled(false);
        ViewPatientRecord2.setOpaque(true);

        ViewPatientRecord2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ViewPatientRecord2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                ViewPatientRecord2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        CreatePrescription2.setBackground(new java.awt.Color(0, 105, 170));
        CreatePrescription2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreatePrescription2.setForeground(new java.awt.Color(255, 255, 255));
        CreatePrescription2.setText("Create Prescription");
        CreatePrescription2.setBorder(null);
        CreatePrescription2.setBorderPainted(false);
        CreatePrescription2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreatePrescription2.setDoubleBuffered(true);
        CreatePrescription2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreatePrescription2.setIconTextGap(50);
        CreatePrescription2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CreatePrescription2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePrescription2ActionPerformed(evt);
            }
        });
        jPanel4.add(CreatePrescription2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 320, 70));
        CreatePrescription2.setFocusPainted(false);
        CreatePrescription2.setBorderPainted(false);
        CreatePrescription2.setContentAreaFilled(false);
        CreatePrescription2.setOpaque(true);

        CreatePrescription2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                CreatePrescription2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                CreatePrescription2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        home.setBackground(new java.awt.Color(0, 105, 170));
        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home ");
        home.setToolTipText("");
        home.setBorder(null);
        home.setBorderPainted(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setDoubleBuffered(true);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setIconTextGap(50);
        home.setName(""); // NOI18N
        home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel4.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 320, 70));
        home.setFocusPainted(false);
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setOpaque(true);

        home.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                home.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                home.setBackground(new Color(0, 120, 200)); // Original color when mouse not hovering
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Doctor");
        jLabel12.setMaximumSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-user-100.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 150, 150));

        AddConsultation2.setBackground(new java.awt.Color(0, 105, 170));
        AddConsultation2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddConsultation2.setForeground(new java.awt.Color(255, 255, 255));
        AddConsultation2.setText("Add Consultation");
        AddConsultation2.setBorder(null);
        AddConsultation2.setBorderPainted(false);
        AddConsultation2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddConsultation2.setDoubleBuffered(true);
        AddConsultation2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddConsultation2.setIconTextGap(50);
        AddConsultation2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddConsultation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddConsultation2ActionPerformed(evt);
            }
        });
        jPanel4.add(AddConsultation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 320, 70));
        CreatePrescription2.setFocusPainted(false);
        CreatePrescription2.setBorderPainted(false);
        CreatePrescription2.setContentAreaFilled(false);
        CreatePrescription2.setOpaque(true);

        CreatePrescription2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                CreatePrescription2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                CreatePrescription2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        RecordVaccination2.setBackground(new java.awt.Color(0, 105, 170));
        RecordVaccination2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RecordVaccination2.setForeground(new java.awt.Color(255, 255, 255));
        RecordVaccination2.setText("Record Vaccination");
        RecordVaccination2.setBorder(null);
        RecordVaccination2.setBorderPainted(false);
        RecordVaccination2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecordVaccination2.setDoubleBuffered(true);
        RecordVaccination2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RecordVaccination2.setIconTextGap(50);
        RecordVaccination2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RecordVaccination2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordVaccination2ActionPerformed(evt);
            }
        });
        jPanel4.add(RecordVaccination2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 320, 70));
        CreatePrescription2.setFocusPainted(false);
        CreatePrescription2.setBorderPainted(false);
        CreatePrescription2.setContentAreaFilled(false);
        CreatePrescription2.setOpaque(true);

        CreatePrescription2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                CreatePrescription2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                CreatePrescription2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 1000));

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1920, 1040));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void colseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colseActionPerformed

        System.exit(0);
    }//GEN-LAST:event_colseActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        //setExtendedState(getExtendedState() | Gérer_Analyse_Medicale.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void RegisterNewPatient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterNewPatient2ActionPerformed
        smoothTransition("client.Chemanage", 1000);
    }//GEN-LAST:event_RegisterNewPatient2ActionPerformed

    private void ViewPatientRecord2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPatientRecord2ActionPerformed
        smoothTransition("client.CheckDoc", 1000);
    }//GEN-LAST:event_ViewPatientRecord2ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        smoothTransition("client.Admin", 1000);

    }//GEN-LAST:event_homeActionPerformed

    private void CreatePrescription2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePrescription2ActionPerformed
       smoothTransition("client.Overview", 1000);
    }//GEN-LAST:event_CreatePrescription2ActionPerformed

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String firstName = first_name.getText().trim();
        String lastName = last_name.getText().trim();

        if (firstName.isEmpty() && lastName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter at least one name");
            return;
        }

        List<String[]> patients = Functions.searchPatient(firstName, lastName);
        DefaultTableModel model = (DefaultTableModel) jTableClient.getModel();

        if (patients.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No patient found with these names");
        } else {
            for (String[] patient : patients) {
                // Check if patient already exists in table (with null safety)
                boolean exists = false;
                for (int i = 0; i < model.getRowCount(); i++) {
                    Object idValue = model.getValueAt(i, 0); // patient_id column
                    if (idValue != null && idValue.toString().equals(patient[0])) {
                        exists = true;
                        break;
                    }
                }

                if (!exists) {
                    model.addRow(new Object[]{
                        patient[0], // patient_id
                        patient[1], // first_name
                        patient[2], // last_name
                        patient[3], // birth_date
                        patient[4]  // social_security_number
                    });
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableClient.getModel();
        model.setRowCount(0); // Clear the table
        first_name.setText(""); // Clear search fields
        last_name.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void AddConsultation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddConsultation2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddConsultation2ActionPerformed

    private void RecordVaccination2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordVaccination2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordVaccination2ActionPerformed
    public static void openProduit(){
    // Open Admin frame
    java.awt.EventQueue.invokeLater(() -> {
       // new Produit().setVisible(true);
    });
     }
    public static void openAjouterCOmpte(){
    // Open Admin frame
    java.awt.EventQueue.invokeLater(() -> {
       // new Ajouter_Compte().setVisible(true);
    });
     }
    
    /**
     * @param args the command line arguments
     */   
    
    private void smoothTransition(String windowName, int delayMilliseconds) {
    // Initialize the Timer outside the EventQueue.invokeLater call
    Timer timer = new Timer(delayMilliseconds, null);

    java.awt.EventQueue.invokeLater(() -> {
        try {
            // Dynamically create an instance of the specified window class
            Class<?> clazz = Class.forName(windowName);
            java.awt.Window window = (java.awt.Window) clazz.getDeclaredConstructor().newInstance();
            
            // Make the window visible
            window.setVisible(true);

            // Update the Timer's ActionListener here
            timer.addActionListener((e) -> {
                // Hide the current window after the delay
                setVisible(false);
                
                // Stop the Timer
                timer.stop();
            });

            // Start the Timer
            timer.start();
        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException ex) {
            // Handle any exceptions
            ex.printStackTrace();
        }
    });
}
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckClient1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddConsultation2;
    private javax.swing.JButton CreatePrescription2;
    private javax.swing.JButton RecordVaccination2;
    private javax.swing.JButton RegisterNewPatient2;
    private javax.swing.JButton ViewPatientRecord2;
    private javax.swing.JButton clear;
    private javax.swing.JButton colse;
    private javax.swing.JTextField first_name;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClient;
    private javax.swing.JTextField last_name;
    private javax.swing.JButton minimize;
    // End of variables declaration//GEN-END:variables
}
