/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.lang.reflect.InvocationTargetException;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author belma
 */
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Medecin
     */
    public Doctor() {
        setIconImage(new ImageIcon(getClass().getResource("/icons/applogo.png")).getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        consultpatientfile2 = new javax.swing.JButton();
        RegisterPatient2 = new javax.swing.JButton();
        RecordVaccination2 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        CreatePrescription2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CreatePrescription1 = new javax.swing.JButton();
        RegisterPatient1 = new javax.swing.JButton();
        consultpatientfile1 = new javax.swing.JButton();
        RecordVaccination1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        colse = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuickLab");
        setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 98, 166));
        jPanel4.setPreferredSize(new java.awt.Dimension(320, 1000));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultpatientfile2.setBackground(new java.awt.Color(0, 105, 170));
        consultpatientfile2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consultpatientfile2.setForeground(new java.awt.Color(255, 255, 255));
        consultpatientfile2.setText("consult a patient's file");
        consultpatientfile2.setToolTipText("");
        consultpatientfile2.setBorder(null);
        consultpatientfile2.setBorderPainted(false);
        consultpatientfile2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultpatientfile2.setDoubleBuffered(true);
        consultpatientfile2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultpatientfile2.setIconTextGap(50);
        consultpatientfile2.setName(""); // NOI18N
        consultpatientfile2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        consultpatientfile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultpatientfile2ActionPerformed(evt);
            }
        });
        jPanel4.add(consultpatientfile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 320, 70));
        consultpatientfile2.setFocusPainted(false);
        consultpatientfile2.setBorderPainted(false);
        consultpatientfile2.setContentAreaFilled(false);
        consultpatientfile2.setOpaque(true);

        consultpatientfile2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                consultpatientfile2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                consultpatientfile2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        RegisterPatient2.setBackground(new java.awt.Color(0, 105, 170));
        RegisterPatient2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegisterPatient2.setForeground(new java.awt.Color(255, 255, 255));
        RegisterPatient2.setText("Register a New Patient");
        RegisterPatient2.setBorder(null);
        RegisterPatient2.setBorderPainted(false);
        RegisterPatient2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterPatient2.setDoubleBuffered(true);
        RegisterPatient2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterPatient2.setIconTextGap(50);
        RegisterPatient2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegisterPatient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPatient2ActionPerformed(evt);
            }
        });
        jPanel4.add(RegisterPatient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 320, 70));
        RegisterPatient2.setFocusPainted(false);
        RegisterPatient2.setBorderPainted(false);
        RegisterPatient2.setContentAreaFilled(false);
        RegisterPatient2.setOpaque(true);

        RegisterPatient2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                RegisterPatient2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                RegisterPatient2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        RecordVaccination2.setBackground(new java.awt.Color(0, 105, 170));
        RecordVaccination2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RecordVaccination2.setForeground(new java.awt.Color(255, 255, 255));
        RecordVaccination2.setText("Record Vaccination");
        RecordVaccination2.setBorder(null);
        RecordVaccination2.setBorderPainted(false);
        RecordVaccination2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecordVaccination2.setDoubleBuffered(true);
        RecordVaccination2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RecordVaccination2.setIconTextGap(50);
        RecordVaccination2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RecordVaccination2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordVaccination2ActionPerformed(evt);
            }
        });
        jPanel4.add(RecordVaccination2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 320, 70));
        RecordVaccination2.setFocusPainted(false);
        RecordVaccination2.setBorderPainted(false);
        RecordVaccination2.setContentAreaFilled(false);
        RecordVaccination2.setOpaque(true);

        RecordVaccination2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                RecordVaccination2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                RecordVaccination2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        home.setBackground(new java.awt.Color(0, 120, 200));
        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.setToolTipText("");
        home.setBorder(null);
        home.setBorderPainted(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setDoubleBuffered(true);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setIconTextGap(50);
        home.setName(""); // NOI18N
        home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel4.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 320, 70));
        home.setFocusPainted(false);
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setOpaque(true);

        home.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                home.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                home.setBackground(new Color(0, 120, 200)); // Original color when mouse not hovering
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Doctor");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-user-100.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 150, 150));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 115, 194));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-log-out-30.png"))); // NOI18N
        logout.setText("Déconnexion");
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setDoubleBuffered(true);
        logout.setIconTextGap(5);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel4.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 901, 220, 60));
        logout.setFocusPainted(false);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.setOpaque(true);
        logout.setBackground(new Color(255, 255, 255)); // Set default background to white

        logout.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                logout.setBackground(new Color(240,240,240)); // Change to light gray on hover
            }

            @Override
            public void mouseExited(MouseEvent e) {
                logout.setBackground(new Color(255, 255, 255)); // Revert to white when not hovered
            }
        });

        CreatePrescription2.setBackground(new java.awt.Color(0, 105, 170));
        CreatePrescription2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreatePrescription2.setForeground(new java.awt.Color(255, 255, 255));
        CreatePrescription2.setText("Create Prescription");
        CreatePrescription2.setBorder(null);
        CreatePrescription2.setBorderPainted(false);
        CreatePrescription2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreatePrescription2.setDoubleBuffered(true);
        CreatePrescription2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreatePrescription2.setIconTextGap(50);
        CreatePrescription2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CreatePrescription2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePrescription2ActionPerformed(evt);
            }
        });
        jPanel4.add(CreatePrescription2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 320, 70));
        RecordVaccination2.setFocusPainted(false);
        RecordVaccination2.setBorderPainted(false);
        RecordVaccination2.setContentAreaFilled(false);
        RecordVaccination2.setOpaque(true);

        RecordVaccination2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                RecordVaccination2.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                RecordVaccination2.setBackground(new Color(0, 105, 170)); // Original color when mouse not hovering
            }
        });

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 1000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMinimumSize(new java.awt.Dimension(1600, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-home-55.png"))); // NOI18N
        jLabel14.setText("Home");
        jLabel14.setIconTextGap(20);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 680, 60));

        CreatePrescription1.setBackground(new java.awt.Color(0, 115, 194));
        CreatePrescription1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CreatePrescription1.setForeground(new java.awt.Color(255, 255, 255));
        CreatePrescription1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-prescription-100.png"))); // NOI18N
        CreatePrescription1.setText("Create Prescription");
        CreatePrescription1.setToolTipText("");
        CreatePrescription1.setBorder(null);
        CreatePrescription1.setBorderPainted(false);
        CreatePrescription1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreatePrescription1.setDoubleBuffered(true);
        CreatePrescription1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreatePrescription1.setIconTextGap(50);
        CreatePrescription1.setName(""); // NOI18N
        CreatePrescription1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CreatePrescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePrescription1ActionPerformed(evt);
            }
        });
        jPanel1.add(CreatePrescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 320, 290));
        RegisterPatient1.setFocusPainted(false);
        RegisterPatient1.setBorderPainted(false);
        RegisterPatient1.setContentAreaFilled(false);
        RegisterPatient1.setOpaque(true);

        RegisterPatient1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                RegisterPatient1.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                RegisterPatient1.setBackground(new Color(0, 115, 194)); // Original color when mouse not hovering
            }
        });

        RegisterPatient1.setBackground(new java.awt.Color(0, 115, 194));
        RegisterPatient1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegisterPatient1.setForeground(new java.awt.Color(255, 255, 255));
        RegisterPatient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-inventory-100.png"))); // NOI18N
        RegisterPatient1.setText("Register a New Patient");
        RegisterPatient1.setBorder(null);
        RegisterPatient1.setBorderPainted(false);
        RegisterPatient1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterPatient1.setDoubleBuffered(true);
        RegisterPatient1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterPatient1.setIconTextGap(50);
        RegisterPatient1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegisterPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPatient1ActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterPatient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 320, 290));
        RegisterPatient1.setFocusPainted(false);
        RegisterPatient1.setBorderPainted(false);
        RegisterPatient1.setContentAreaFilled(false);
        RegisterPatient1.setOpaque(true);

        RegisterPatient1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                RegisterPatient1.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                RegisterPatient1.setBackground(new Color(0, 115, 194)); // Original color when mouse not hovering
            }
        });

        consultpatientfile1.setBackground(new java.awt.Color(0, 115, 194));
        consultpatientfile1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        consultpatientfile1.setForeground(new java.awt.Color(255, 255, 255));
        consultpatientfile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-medical-history-100.png"))); // NOI18N
        consultpatientfile1.setText("consult a patient's file");
        consultpatientfile1.setBorder(null);
        consultpatientfile1.setBorderPainted(false);
        consultpatientfile1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultpatientfile1.setDoubleBuffered(true);
        consultpatientfile1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultpatientfile1.setIconTextGap(50);
        consultpatientfile1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        consultpatientfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultpatientfile1ActionPerformed(evt);
            }
        });
        jPanel1.add(consultpatientfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 370, 320, 290));
        consultpatientfile1.setFocusPainted(false);
        consultpatientfile1.setBorderPainted(false);
        consultpatientfile1.setContentAreaFilled(false);
        consultpatientfile1.setOpaque(true);

        consultpatientfile1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                consultpatientfile1.setBackground(new Color(23,142,224)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                consultpatientfile1.setBackground(new Color(0, 115, 194)); // Original color when mouse not hovering
            }
        });

        RecordVaccination1.setBackground(new java.awt.Color(0, 115, 194));
        RecordVaccination1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RecordVaccination1.setForeground(new java.awt.Color(255, 255, 255));
        RecordVaccination1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-vaccination-100.png"))); // NOI18N
        RecordVaccination1.setText("Record Vaccination");
        RecordVaccination1.setToolTipText("");
        RecordVaccination1.setBorder(null);
        RecordVaccination1.setBorderPainted(false);
        RecordVaccination1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecordVaccination1.setDoubleBuffered(true);
        RecordVaccination1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RecordVaccination1.setIconTextGap(50);
        RecordVaccination1.setName(""); // NOI18N
        RecordVaccination1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RecordVaccination1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordVaccination1ActionPerformed(evt);
            }
        });
        jPanel1.add(RecordVaccination1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 320, 290));
        CreatePrescription1.setFocusPainted(false);
        CreatePrescription1.setBorderPainted(false);
        CreatePrescription1.setContentAreaFilled(true);
        CreatePrescription1.setOpaque(true);
        CreatePrescription1.setRolloverEnabled(false); // <--- add this line
        CreatePrescription1.setBackground(new Color(0, 115, 194)); // Normal background

        CreatePrescription1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                CreatePrescription1.setBackground(new Color(23,142,224)); // Hover color
            }

            @Override
            public void mouseExited(MouseEvent e) {
                CreatePrescription1.setBackground(new Color(0, 115, 194)); // Back to normal
            }
        });

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 1600, 1000));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(0, 0, 0));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-minimize-30.png"))); // NOI18N
        minimize.setBorder(null);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 0, 40, 40));
        minimize.setFocusPainted(false);
        minimize.setBorderPainted(false);
        minimize.setContentAreaFilled(false);
        minimize.setOpaque(true);

        minimize.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                minimize.setBackground(new Color(20,20,20)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                minimize.setBackground(new Color(0, 0,0)); // Original color when mouse not hovering
            }
        });

        colse.setBackground(new java.awt.Color(0, 0, 0));
        colse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerant icons/icons8-close-30.png"))); // NOI18N
        colse.setBorder(null);
        colse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colseActionPerformed(evt);
            }
        });
        jPanel2.add(colse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 0, 40, 40));
        colse.setFocusPainted(false);
        colse.setBorderPainted(false);
        colse.setContentAreaFilled(false);
        colse.setOpaque(true);

        colse.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                colse.setBackground(new Color(20,20,20)); // Darker blue when mouse hovers
            }

            @Override
            public void mouseExited(MouseEvent e) {
                colse.setBackground(new Color(0, 0,0)); // Original color when mouse not hovering
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("QuickLab");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 40));

        setSize(new java.awt.Dimension(1920, 1040));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultpatientfile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultpatientfile2ActionPerformed
        smoothTransition("client.Gérer_Analyse_Medicale", 1000);
    }//GEN-LAST:event_consultpatientfile2ActionPerformed

    private void RegisterPatient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPatient2ActionPerformed
        smoothTransition("client.Produit", 1000, "medecin");

    }//GEN-LAST:event_RegisterPatient2ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

          smoothTransition("client.Medecin", 500);


    }//GEN-LAST:event_homeActionPerformed

    private void RecordVaccination2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordVaccination2ActionPerformed
        smoothTransition("client.Dossier", 1000, "medecin");
    }//GEN-LAST:event_RecordVaccination2ActionPerformed

    private void RegisterPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPatient1ActionPerformed
        smoothTransition("client.Produit", 1000, "medecin");

    }//GEN-LAST:event_RegisterPatient1ActionPerformed

    private void consultpatientfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultpatientfile1ActionPerformed
        smoothTransition("client.Dossier", 1000, "medecin");
    }//GEN-LAST:event_consultpatientfile1ActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        //setExtendedState(getExtendedState() | Gérer_Analyse_Medicale.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void colseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colseActionPerformed

        System.exit(0);
    }//GEN-LAST:event_colseActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void CreatePrescription2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePrescription2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePrescription2ActionPerformed

    private void RecordVaccination1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordVaccination1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordVaccination1ActionPerformed

    private void CreatePrescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePrescription1ActionPerformed

        smoothTransition("client.Gérer_Analyse_Medicale", 1000);
    }//GEN-LAST:event_CreatePrescription1ActionPerformed
    
     public static void openProduit(){
    // Open Gerant frame
    
    java.awt.EventQueue.invokeLater(() -> {
       // new Produit("medecin").setVisible(true);
    });
     }
    
    public static void openGérerAnalyseMedicale(){
    // Open Gerant frame
    java.awt.EventQueue.invokeLater(() -> {
        //new Gérer_Analyse_Medicale().setVisible(true);
    });
     }
    
//By: OussamaDeV


private void smoothTransition(String windowName, int delayMilliseconds) {
    // Initialize the Timer outside the EventQueue.invokeLater call
    Timer timer = new Timer(delayMilliseconds, null);

    java.awt.EventQueue.invokeLater(() -> {
        try {
            // Dynamically create an instance of the specified window class
            Class<?> clazz = Class.forName(windowName);
            java.awt.Window window = (java.awt.Window) clazz.getDeclaredConstructor().newInstance();
            
            // Make the window visible
            window.setVisible(true);

            // Update the Timer's ActionListener here
            timer.addActionListener((e) -> {
                // Hide the current window after the delay
                setVisible(false);
                
                // Stop the Timer
                timer.stop();
            });

            // Start the Timer
            timer.start();
        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException ex) {
            // Handle any exceptions
            ex.printStackTrace();
        }
    });
}
    
    
private void smoothTransition(String windowName, int delayMilliseconds, Object... constructorArgs) {
    // Initialize the Timer outside the EventQueue.invokeLater call
    Timer timer = new Timer(delayMilliseconds, null);

    java.awt.EventQueue.invokeLater(() -> {
        try {
            // Dynamically create an instance of the specified window class
            Class<?> clazz = Class.forName(windowName);
            // Determine parameter types from constructorArgs
            Class<?>[] parameterTypes = new Class<?>[constructorArgs.length];
            for (int i = 0; i < constructorArgs.length; i++) {
                parameterTypes[i] = constructorArgs[i].getClass();
            }
            java.awt.Window window = (java.awt.Window) clazz.getDeclaredConstructor(parameterTypes).newInstance(constructorArgs);
            
            // Make the window visible
            window.setVisible(true);

            // Update the Timer's ActionListener here
            timer.addActionListener((e) -> {
                // Hide the current window after the delay
                setVisible(false);
                
                // Stop the Timer
                timer.stop();
            });

            // Start the Timer
            timer.start();
        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException ex) {
            // Handle any exceptions
            ex.printStackTrace();
        }
    });
}    
    
    
    
    /**
     * @param args the command line arguments
     */
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatePrescription1;
    private javax.swing.JButton CreatePrescription2;
    private javax.swing.JButton RecordVaccination1;
    private javax.swing.JButton RecordVaccination2;
    private javax.swing.JButton RegisterPatient1;
    private javax.swing.JButton RegisterPatient2;
    private javax.swing.JButton colse;
    private javax.swing.JButton consultpatientfile1;
    private javax.swing.JButton consultpatientfile2;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JButton minimize;
    // End of variables declaration//GEN-END:variables
}
